# Site settings
title: Luiz Felipe Pedone
email: luiz.pedone@gmail.com
description: "Hi! My name is Luiz Felipe Pedone and I'm a web developer."
permalink: posts/:title
markdown: kramdown
url: luizpedone.com
